version: '3.1'

services:
  db:
    image: mysql:8.0.36
    container_name: ocai
    environment:
      MYSQL_ROOT_PASSWORD: OcaiApi@25
      MYSQL_DATABASE: ocai-api
    ports:
      - "3070:3306"
    volumes:
      - dbdata:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: ocai_pma
    platform: linux/amd64
    environment:
      PMA_HOST: ocai
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8085:80
volumes:
  dbdata: